### ISSUE TITLE
Sending multiple alternative languages 

### ISSUE THREAD

**Issue by karan-k1110** [GoogleCloudPlatform/cpp-samples#101]
Hey,
I'm using Google speech to text's v1p1beta1 library, which enabled me to send alternative language with a primary language. For one primary language it is working completely fine. But I'm not able to figure out how to send multiple alternative language ? Google's documentation states that upto 3 alternative languages can be sent.

**Comment by coryan** [comment]
I do not think we can help you here, this repository hosts some examples on how to use C++ and the GCP speech service, but we are far from experts on how the service works. Have you tried the GCP community slack and/or stackoverflow?

**Comment by karan-k1110** [comment]
I tried stackoverflow but no luck, what's the link to community slack?

**Comment by coryan** [comment]
I think https://googlecloud-community.slack.com

**Comment by ArthurVerstraete** [comment]
Hi, is there already a fix for this? I tried using config->set_alternative_language_codes but this function doesn't exist while the official Google Speech to Text documentation is saying this should exist
