### ISSUE TITLE
c++ speech sample question.

### ISSUE THREAD

**Issue by PIAOTJ** [GoogleCloudPlatform/cpp-samples#102]
hello. i'm beginner.

i'm trying to build this sample. but i can't build and run this sample.

[](https://github.com/GoogleCloudPlatform/cpp-samples/tree/master/speech/api)

i'm install gRPC, and protobuf, and i try build

7. Generate googleapis gRPC source code.

but filed to make, and I try use bezel build success.

but when i try 8. 9. i'm can't build 

   - cd cpp-docs-samples/speech/api
   - make run_tests

error is log.severity.pb.h is not found.

+ i'm usinb grpc 1.30.0

my question is..

now, this sample is can build? and run?

thank you.

**Comment by coryan** [comment]
I am not sure if this helps.  It seems the instructions are extremely outdated, I will try to get somebody interested in fixing them.  Meanwhile: the makefiles in `speech/api` depend on successfully running `make` in step 7, can you tell us *how* those instructions failed? Also please include the following information:

- This example has only been tested on Linux, please tell us what version of Linux are you using.
- What version of protobuf did you use?
- Where is protobuf (and most importantly `protoc`) installed?
- Is `protoc` in your `$PATH`?  The `googleapis/googleapis/Makefile` requires changes if this is not the case.
 
> now, this sample is can build? and run?

It does, but with relatively old versions of gRPC, protobuf, and googleapis. You are trying to use it with much newer versions.

**Comment by PIAOTJ** [comment]
> I am not sure if this helps. It seems the instructions are extremely outdated, I will try to get somebody interested in fixing them. Meanwhile: the makefiles in `speech/api` depend on successfully running `make` in step 7, can you tell us _how_ those instructions failed? Also please include the following information:
> 
> * This example has only been tested on Linux, please tell us what version of Linux are you using.
> * What version of protobuf did you use?
> * Where is protobuf (and most importantly `protoc`) installed?
> * Is `protoc` in your `$PATH`?  The `googleapis/googleapis/Makefile` requires changes if this is not the case.
> 
> > now, this sample is can build? and run?
> 
> It does, but with relatively old versions of gRPC, protobuf, and googleapis. You are trying to use it with much newer versions.

**Comment by PIAOTJ** [comment]
thanks, coryan.

i'm failed to build thils sample use grpc 1.30.0
so i retry grpc 1.26.0

1. i'm use linux ubuntu 16.04.
2. now i'm using grpc 1.26.0, protoc 3.8.0, 
3. protoc is in /usr/local/bin
4. yes

grpc 1.26.0 i'm success build googleapis and this sample.

i have another question.

i'm try to run_tests but not response anything.

i open transcribe.cc and

 > auto creds = grpc::GoogleDefaultCredentials();

seems this line not working.

i already set export GOOGLE_APPLICATION_CREDENTIALS=/path/to/your/credentials-key.json

please help. thank you.

**Comment by coryan** [comment]
> 
> grpc 1.26.0 i'm success build googleapis and this sample.

Yay! 🎉 

> 
> i have another question.
> 
> i'm try to run_tests but not response anything.
> 
> i open transcribe.cc and
> 
> > auto creds = grpc::GoogleDefaultCredentials();
> 
> seems this line not working.

Okay, this is probably more of an authentication problem.  You probably tried the ideas below, but in case you have not.   I would try to follow the speech-to-text quickstart first:

https://cloud.google.com/speech-to-text/docs/quickstart-gcloud

Once that works then probably your problems with `grpc::GoogleDefaultCredentials()` would go away.  You may also want to learn about authentication about GCP:

https://cloud.google.com/docs/authentication

**Comment by PIAOTJ** [comment]
hi, coryan.

i retry 1.26.x (not 1.26.0 release, 1.26.0 has bug)
[https://github.com/grpc/grpc/tree/v1.26.x](https://github.com/grpc/grpc/tree/v1.26.x )

i finally success run this sample.

thank you!
