### ISSUE TITLE
Running the examples - grpc error

### ISSUE THREAD

**Issue by trajcenikolovnick** [GoogleCloudPlatform/cpp-samples#170]
Hi Community,

I managed to build and run the samples and here is what it says - WIndows 10. Any hints? Thank you

E:\cpp-samples\speech\api>.build\Debug\streaming_transcribe.exe resources\audio.flac
E0129 12:07:34.646000000 37120 ssl_utils.cc:592] load_file: {"created":"@1643450854.646000000","description":"Failed to load file","file":"E:\vcpkg\buildtrees\grpc\src\2180080eb4-87c05d756b.clean\src\core\lib\iomgr\load_file.cc","file_line":72,"filename":"/usr/share/grpc/roots.pem","referenced_errors":[{"created":"@1643450854.646000000","description":"No such file or directory","errno":2,"file":"E:\vcpkg\buildtrees\grpc\src\2180080eb4-87c05d756b.clean\src\core\lib\iomgr\load_file.cc","file_line":45,"os_error":"No such file or directory","syscall":"fopen"}]}
E0129 12:07:34.680000000 37120 ssl_security_connector.cc:420] Could not get default pem root certs.
E0129 12:07:34.687000000 37120 secure_channel_create.cc:107] Failed to create secure subchannel for secure name 'speech.googleapis.com'
E0129 12:07:34.693000000 37120 secure_channel_create.cc:49] Failed to create channel args during subchannel creation.
E0129 12:07:34.698000000 37120 ssl_security_connector.cc:420] Could not get default pem root certs.
E0129 12:07:34.702000000 37120 secure_channel_create.cc:107] Failed to create secure subchannel for secure name 'speech.googleapis.com'

**Comment by trajcenikolovnick** [comment]
I figured out that it is set up for Linux. I made my own folder \usr\share\grpc\ and put the certificate there and it worked. Any more elegant way to set the path to the certificate?

**Comment by coryan** [comment]
On Windows gRPC needs a `roots.pem` file to complete the SSL handshake:

https://github.com/googleapis/google-cloud-cpp/tree/main/google/cloud/texttospeech/quickstart#windows

**Comment by coryan** [comment]
FWIW, we are planning to add the speech client library to https://github.com/googleapis/google-cloud-cpp and we typically document how to configure things for Windows and macOS when we create libraries there.

**Comment by trajcenikolovnick** [comment]
Thanks! I am fine now. You can close the issue

**Comment by coryan** [comment]
Glad things are working.  I just sent #171 for review to make this easier in the future.
