### ISSUE TITLE
Jwt.h on example

### ISSUE THREAD

**Issue by simogaspa84** [GoogleCloudPlatform/cpp-samples#172]
Hi... Can you please attach here the example where is located or the library for the jwt code you used ? 

Thanks a lo t

**Comment by coryan** [comment]
Is this regarding this example https://github.com/GoogleCloudPlatform/cpp-samples/tree/main/iot/mqtt-ciotc ?

We use https://github.com/benmcollins/libjwt

You can see how it is downloaded in the corresponding `CMake` file:

https://github.com/GoogleCloudPlatform/cpp-samples/blob/161e068162a8f97a21011001d20450688979365d/iot/mqtt-ciotc/CMakeLists.txt#L29-L38
