### ISSUE TITLE
Trouble creating a Google Cloud Speech to Text Client using  

### ISSUE THREAD

**Issue by cdelsordo** [GoogleCloudPlatform/cpp-samples#173]
I am working on a Comcast RDK streamer product and we were looking to add a C++ Google Cloud Speech to Text Client to transcribe voice commands.  I tried following the README.md instructions for github.com/GoogleCloudPlatform/cpp-samples/tree/main/speech/api and it said that I need to start by installing vcpkg.  Looking at those instructions it seems that is very difficult to add to the RDK yocto environment due to the fact that it is not a typical linux os environment (it is embedded) like CENTOS..  Is there an alternative to using vcpkg?

**Comment by coryan** [comment]
> Is there an alternative to using vcpkg?

Yes.  `vcpkg` is a good way to get started and run the samples, but we do not require that you use it.  First, I think you may want to take a look at the C++ client libraries:

https://github.com/googleapis/google-cloud-cpp

which are gaining support for Speech-to-Text "soon":

https://github.com/googleapis/google-cloud-cpp/tree/main/google/cloud/speech

The client libraries include step-by-step instructions to compile them in a variety of platforms:

https://github.com/googleapis/google-cloud-cpp/blob/main/doc/packaging.md

The list of platforms includes CentOS, which I hope would be a good start for what you want.  Even if you decide not to use the client libraries and use the gRPC APIs directly, those instructions should help you compile gRPC and its dependencies.

**Comment by coryan** [comment]
I am going to close this as the question seems to be answered.
