### ISSUE TITLE
How to set speech language in streaming_transcribe 

### ISSUE THREAD

**Issue by lichao252244354** [GoogleCloudPlatform/cpp-samples#201]
Hello , Could you please tell me where can I set the recognition language Japanese or korean in streaming_transcribe ,which API can set the speech language,thank you

**Comment by coryan** [comment]
This kind of question is better answered by the reference documentation and guides than by the samples.  A good starting point is:

https://cloud.google.com/speech-to-text/docs

The list of supported languages is found here:

https://cloud.google.com/speech-to-text/docs/languages

In the C++ examples this is configured here:

https://github.com/GoogleCloudPlatform/cpp-samples/blob/main/speech/api/parse_arguments.cc#L63

The full reference documentation for the protos is found here:

https://cloud.google.com/speech-to-text/docs/reference/rpc/google.cloud.speech.v1

And the full reference documentation for the C++ client API is found here:

https://googleapis.dev/cpp/google-cloud-speech/latest/

**Comment by lichao252244354** [comment]
thank you very much , I can use the command streaming_transcribe.exe --language-code ko-KR D:\resource\KoRean \2.wav test KoRean audio file .but  have no recognizer Result return

**Comment by coryan** [comment]
I am not a Cloud Text-to-Speech expert.  The best I can do is offer some general troubleshooting guidance.  I tested with a public file in `es-ES` encoding:

```shell
gsutil cp gs://cloud-samples-data/speech/multi_es.flac .
streaming_transcribe --language-code=es-ES --bitrate=44100 multi_es.flac
```

That worked for me.  That leads me to believe that setting the language encoding in the examples "works", in that it is sent and interpreted correctly by the service.  In your place I would try to use an existing tool to see if it works, for example, try using the `gcloud` command-line tool:

https://cloud.google.com/speech-to-text/docs/transcribe-gcloud#make_an_audio_transcription_request

I think in your case you would try:

```shell
gcloud ml speech recognize --language-code ko-KR "D:\resource\KoRean \2.wav"
```

Note the use of quotes around a filename with spaces in it.

If using `gcloud` does not work, then it is a problem with the service.  I think you would need to contact support in that case.

If `gcloud` does work, then it is probably the examples.  With the current version of the examples you can use some environment variables to troubleshoot the messages.  On Windows that would be:

```shell
set GOOGLE_CLOUD_CPP_ENABLE_CLOG=yes
set GOOGLE_CLOUD_CPP_ENABLE_TRACING=rpc,rpc-streams
```

and then run the commands as before.

**Comment by lichao252244354** [comment]
thank you very much ,I will do the relevant tests as you suggest

**Comment by coryan** [comment]
Closing for now, please reopen if you have more questions on this topic.
