### ISSUE TITLE
 Google cloud speech library is  static library

### ISSUE THREAD

**Issue by lichao252244354** [GoogleCloudPlatform/cpp-samples#202]
Hello .when I use vcpkg install google cloud speech library ,I found the packages all are .lib，cloud you help me  how to get the .dll library ,I want to compile into dll in my project ,thank you very much

**Comment by coryan** [comment]
This is not possible at the moment, the rationale is explained at:

https://github.com/googleapis/google-cloud-cpp/issues/5849
