### ISSUE TITLE
IoT Core wrong topic on publish

### ISSUE THREAD

**Issue by asanchezdelc** [GoogleCloudPlatform/cpp-samples#31]
https://github.com/GoogleCloudPlatform/cpp-docs-samples/tree/master/iot/mqtt-ciotc

The example that connects and publish data to the core, its publishing data to: 

`/devices/mqtt-c-rsq2/events` instead, it should be: `/devices/{device-id}/events`. It looks like its using the hardcoded value under `opts.topic`.

**Comment by gguuss** [comment]
Thanks for the heads up, I'll take a look while adding exponential backoff, maybe you're passing the --deviceid as the first parameter?

**Comment by HMS-LIG** [comment]
This is still broken as far as I can see. The example client now publishes to the hardcoded topic ""/devices/{your-device-id}/events"" as opts.topic is never changes from its initial string. Trying out the example results in an error notification on my registered device in the GCP stating:

> mqtt: PUBLISH:Unauthorized MQTT publish topic: /devices/{your-device-id}/events, expects /devices/{device-id}/events

Looks like the only way to get it to publish to the correct topic is to manually modify the .topic = "/devices/{your-device-id}/events" string in the example code and rebuild.

The example code is referenced from documentation on page https://cloud.google.com/iot/docs/samples/mqtt-samples as the C example.

**Comment by SurferJeffAtGoogle** [comment]
Thank your the update.  It looks like you did the right thing.

I did not write the sample, but I think the author actually intended for readers to modify the source code like you did.  Do you see a way to better communicate that to the reader?  Or perhaps, to not require the reader to modify the source code?

**Comment by HMS-LIG** [comment]
I looked at the instructions provided in https://github.com/GoogleCloudPlatform/cpp-docs-samples/blob/master/iot/mqtt-ciotc/README.md and from reading that I don't think the (current) intention is to modify the source code as you can/must provide the different options on the command line, --deviceid for example (bottom of README). The MQTT topic must be automatically assembled from the deviceid you supply as command option.

I made a fix in line with the existing code that could be used for inspiration (not sure if I can accept the corporate CLA without approvement, so cant create a pull request yet) here:
https://github.com/HMS-LIG/cpp-docs-samples/commit/1eb86de3003f129acf76ea0b06773efb3f042edf

**Comment by gguuss** [comment]
It's been a while since I last looked at the code here but the intention originally had been to support command-line parameters for the sample once it had been built. I'm not sure I actually tested it very thoroughly and I recall fixing an off-by-one bug on the ordered parameters.

**Comment by gguuss** [comment]
This should be fixed in:

https://github.com/GoogleCloudPlatform/cpp-docs-samples/pull/46
