### ISSUE TITLE
Run tests for iot sample

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/cpp-samples#65]

**Comment by tmatsuo** [comment]
#66 will add a basic ci build for iot sample which only builds the sample code. It's definitely better if we have real tests and run them in the ci builds.

**Comment by tmatsuo** [comment]
@gguuss Can you take this? Just let me know if you can not.

**Comment by gguuss** [comment]
I'm pretty busy for the next few weeks, if you can take it, it's appreciated!

**Comment by tmatsuo** [comment]
@gguuss 

I'm trying to use setup_device.sh, but I'm having trouble running it.

What should I use for `${REGISTRY_TELEMETRY_TOPIC}` on this line https://github.com/GoogleCloudPlatform/cpp-samples/blob/fe3ec170c1afee60dcf6ef97aa76bb960d888716/iot/mqtt-ciotc/setup_device.sh#L73?

**Comment by tmatsuo** [comment]
@gguuss nm I figured it out. I think I need to create a topic beforehand.
