### ISSUE TITLE
Use time.google.com for iat

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/cpp-samples#72]
https://github.com/GoogleCloudPlatform/cpp-samples/blob/66f49119fe844a6cd75bb2560b02b82462bacd61/iot/mqtt-ciotc/mqtt_ciotc.c#L77

**Comment by tmatsuo** [comment]
I created this issue because I found a TODO in the code. Can you clarify a bit more?

**Comment by gguuss** [comment]
We should be using the Google time server (using NTP) and I didn't want to ship the code for performing an NTP call.

**Comment by tmatsuo** [comment]
Is it just about configuring NTP on the host machine?

**Comment by gguuss** [comment]
It could be as simple as that but I am thinking about cases where the C++ is used in bare-metal like environments. [Here is an example implementation in C](https://github.com/lettier/ntpclient/blob/master/source/c/main.c).

**Comment by sgreenberg** [comment]
At this point in time, we don't have the folks available to address feature requests in IoT.
